// 40 most famous animal noun in singapore zoo 
export const words = [
    "elephant",
    "orangutan",
    "giraffe",
    "zebra",
    "lion",
    "tiger",
    "cheetah",
    // "leopard",
    // "panda",
    // "rhinoceros",
    // "hippopotamus",
    // "flamingo",
    // "peacock",
    // "penguin",
    // "kangaroo",
    // "koala",
    // "crocodile",
    // "python",
    // "iguana",
    // "tapir",
    // "capybara",
    // "lemur",
    // "meerkat",
    // "otter",
    // "sloth",
    // "wolf",
    // "fox",
    // "vulture",
    // "parrot",
    // "toucan",
    // "macaw",
    // "komodo",
    // "armadillo",
    // "anteater",
    // "jaguar",
    // "baboon",
    // "mandrill",
    // "porcupine",
    // "aardvark",
    // "wallaby"
];
